Dev
whiteWolfx99/Capstone_js pull request #36
Opened 2022-11-24 21:37 UTC by whiteWolfx99

# code review

2022-11-24 21:57 UTC, Ismailco reviewed
Hi @whiteWolfx99, @emmanuellmhango, @amexabee, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that uses an old version of README, kindly consider using the new README template provided by microverse for more professional documentation of your work

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-11-25 00:40 UTC, Alfredbis29 requested changes
## Hello Team,
 I'm Alfred your reviewer for this PR :man_beard:
 
 Great work working on your project so far! :clap: There are some issues that you still need to work on to go to the next project but you are almost there!
 
 ![](https://camo.githubusercontent.com/4f9601b422a77702aefe8e13485d2d5618cc0c30772eb2aa9f4129eac4757e06/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f4b7942657366386b4e5436733838534567622f67697068792e676966) 

 ## Highlights
Great job setting up the correct linters :heavy_check_mark:
 Meaningful commit messages :heavy_check_mark:
Set up the repository on GitHub and use Gitflow :heavy_check_mark: 
 
 ##  Required Changes :black_circle: 
 

- [ ] As we are on day three of your project, you must complete the following requirements in order for your project to be completed :point_down: 
**Day** 3
Complete the work on individual interfaces.
Record a video for your project.
Create a good README and PR description.
Ask for the external review - using your Student Dashboard.

But I can't see where you record the video , kindly record a video where every member of the group explain his own contribution and the part he/she feels proud :wink: 

 _Check the comments under the review._
 
 ## [Optional] suggestions

- [ ] I recommend that you verify this as well. The images are not displaying on your card products; please address this so that your project appears professional and attractive.:wink: 

![imagenot](https://user-images.githubusercontent.com/88894525/203878435-34835d7a-df96-43bd-bc0b-e24284658412.png)
 

 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

 Cheers and Happy coding! :partying_face: :clap: :clap:

 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me  in your question so I can receive the notification.

 **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
 
 _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-25 01:04 UTC, emmanuellmhango commented on src/Test/Likes.test.js
> +});
Dear @Alfredbis29 ,

As I had explained on the call, and also on the requirements, the video is on Day 4, not 3. and today is Day 3.

Below is the requirements for Day 3:

**Day 3**
- Complete the work on individual interfaces.
- Create a good README.
- Ask for the external review - using your Student Dashboard.

Based on the requirements, may you please comment on the individual requirement so as to what is missing in the project?

2022-11-25 05:48 UTC, whiteWolfx99 commented on src/Test/Likes.test.js
> +});
hi @Alfredbis29, My test is workingon my side; I'm not sure why it isn't working on yours; it also works on my coding partner's side; I believe the problem is that you haven't run **npm i isomorphic-fetch**; please paste this in terminal to see whether the test passes.

2022-11-25 07:23 UTC, Alfredbis29 commented on src/Test/Likes.test.js
> +});
Hello @whiteWolfx99  @emmanuellmhango , I hope you are doing well and appreciate your patience. I apologize for asking you to record a video when it should have been for day 4 of your project. However, I recommend that you correct the problem that is preventing the test from passing before you ask a second review. thanks and good luck :wink:  :smiling_face_with_tear:

2022-11-25 13:57 UTC, emmanuellmhango commented on src/Test/Likes.test.js
> +});
Dear @Alfredbis29 , SInce the REQUIRED changes you indicated was the video presentation, and the tests were OPTIONAL,, would you please then go ahead and approve it, we would really appreciate that as we were stuck going ahead because you had overlooked the video requirement that it wasn't needed?

2022-11-25 17:01 UTC, Deepakdanger approved these changes
Hi @TEAM, 

### Status: Approved ✔️

Your project is complete!  There is nothing else to say other than... it's time to merge it  🚢 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-25 17:02 UTC, merged